services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=${APP_PORT}
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
