services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

    networks:
      - coolify

networks:
  coolify:
    external: true
